[project]
name = "production-ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "langchain>=1.4.0",
    "langchain-anthropic>=1.7.1",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-ollama>=1.1.0",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "pypdf>=6.18.1",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
]
